### ISSUE TITLE
Create controller and views for Tasks

### ISSUE THREAD

**Issue by pbaisla** [pbaisla/todo-webapp#3]
Create a controller `TaskController` having the following actions:
- `index` Show all tasks of a user
- `show` Show a particular task
- `new` Form for creating a new task
- `create` Create new task
- `edit` Form for editing a task
- `update` Update task
- `destroy` Delete a task

We also need views for the following actions:
- `index`
- `show`
- `new`
- `edit`

**Comment by TejaKilaru** [comment]
Completed with #6
